# -*- mode: ruby -*-
# vi: set ft=ruby :
#
IMAGE_NAME = "bento/ubuntu-16.04"
N = 2

Vagrant.configure("2") do |config|
  	if Vagrant.has_plugin?("vagrant-proxyconf")
  	  config.proxy.http     = "http://192.168.0.107:8118/"  # 本机代理ip端口
  	  config.proxy.https    = "http://192.168.0.107:8118/"  
  	  config.proxy.no_proxy = "0,1,2,3,4,5,6,7,8,9,10.0.0.0/8,https://10.0.0.20,https://10.0.0.11, https://10.0.0.12"
  	end
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "10.0.0.20"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "10.0.0.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
            end
        end
    end
end
